### PR TITLE
Fix sparkles recipe

### LINKED ISSUE #116: sparkles conda package will not build without SKA defined
sparkles conda package will not build without SKA defined.

```
Ignoring indexes: https://pypi.python.org/simple
Processing /export/aca/skare3/builds/sparkles_1551797816731/work
  Running setup.py (path:/tmp/pip-rbuc01t1-build/setup.py) egg_info for package from file:///export/aca/skare3/builds/sparkles_1551797816731/work
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-rbuc01t1-build/setup.py", line 1, in <module>
        from sparkles import __version__
      File "/tmp/pip-rbuc01t1-build/sparkles/__init__.py", line 3, in <module>
        from .core import run_aca_review, ACAReviewTable
      File "/tmp/pip-rbuc01t1-build/sparkles/core.py", line 29, in <module>
        from proseco.catalog import ACATable
      File "/export/aca/skare3/builds/sparkles_1551797816731/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.6/site-packages/proseco/catalog.py", line 7, in <module>
        from .core import ACACatalogTable, get_kwargs_from_starcheck_text, MetaAttribute
      File "/export/aca/skare3/builds/sparkles_1551797816731/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.6/site-packages/proseco/core.py", line 20, in <module>
        from mica.archive.aca_dark import get_dark_cal_image
      File "/export/aca/skare3/builds/sparkles_1551797816731/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.6/site-packages/mica/archive/aca_dark/__init__.py", line 2, in <module>
        from .dark_cal import *
      File "/export/aca/skare3/builds/sparkles_1551797816731/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.6/site-packages/mica/archive/aca_dark/dark_cal.py", line 19, in <module>
        from mica.common import MICA_ARCHIVE_PATH, MissingDataError
      File "/export/aca/skare3/builds/sparkles_1551797816731/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.6/site-packages/mica/common.py", line 11, in <module>
        FLIGHT_MICA_ARCHIVE = os.path.join(os.environ['SKA'], 'data', 'mica', 'archive')
      File "/export/aca/skare3/builds/sparkles_1551797816731/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.6/os.py", line 669, in __getitem__
        raise KeyError(key) from None
    KeyError: 'SKA'
```

### PR DESCRIPTION
**Pull request by jeanconn**
Fix sparkles recipe

Closes #116

### CODE REVIEW

File: pkg_defs/sparkles/build.sh [hunk 1]
```diff
@@ -1 +1,2 @@
-pip install --no-deps --verbose --no-binary :all: --no-index .
\ No newline at end of file
+export SKA=/dev/null
```
Comment (jeanconn) [inline pkg_defs/sparkles/build.sh]: For building, I think we can set it to anything and are probably better off not setting it to an actual ska.  @taldcroft do you have any thoughts on this?

Comment (taldcroft) [reply pkg_defs/sparkles/build.sh]: That seems fine.  Hopefully in the next release we will have a nicer plan in place, but as long as it builds and installs and tests, then whatever.
